### ISSUE TITLE
Rescue Spouse

### ISSUE THREAD

**Issue by oddlittleturtle** [oddlittleturtle/TabulaRasa#17]
The idea of rescuing the spouse and having them as one of the companions is compelling but it is a very advanced feature that would take much longer to implement.

**Task List:**

- [ ] Rescue Spouse: Dialogue checks for spouse as a companion
- [ ] Rescue Spouse: Scripting enhancements that work with Unofficial patch instead of against it
- [ ] Rescue Spouse: Spouse affinity
- [ ] Rescue Spouse: Spouse speaks to Valentine, Mama Murphy, and others during Wastelander start instead of the player
